# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    paths-ignore: ['pom.xml', '.*']
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Delete old package versions
      uses: smartsquaregmbh/delete-old-packages@v0.3.1
      with:
        names: |
          me._4o4.vplanwrapper
        keep: 5

    - name: Update Version
      run: mvn -B release:update-versions
      
    - name: Echo Repo URL
      run: echo 'github.com/${{github.repository}}.git'
      
    - name: Echo working dir
      run: echo ${{ github.workspace }}
      
    - name: Push updated version
      uses: actions-x/commit@v2
      with:
        name: bot
        email: bot@github.com
        files: pom.xml
        repository: 'https://github.com/${{github.repository}}'
        token: ${{ secrets.COMMIT_TOKEN }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
