# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    paths-ignore: 'pom.xml'
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Configure Git user  
      run: |
       git config user.email "actions@github.com"
       git config user.name "GitHub Actions"
    - name: Build with Maven
      run: mvn -B release:prepare release:perform
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
